### PR TITLE
Add proper instructions to install on windows

### PR DESCRIPTION
**Pull request by azawawi**

### CODE REVIEW

**Comment by ugexe** [comment]
I mentioned in the other issue, but I will mention here as well. Windows is not expected to have a different install procedure; something is wrong if you cannot clone zef into any directory and have it work. On my machine I can clone zef into `C:\tools` (I don't have a separate drive.. so I can't test a separate `D:\` disk) and it installs ok using the default install instructions. In the latest changes a `.zef` (note: dot zef) directory is created but *only* for the package list to be saved to; zef itself is not meant to be saved here.

Any other ideas what it could be? I keep thinking it has to be related to `git` and how it saves/fetches the package list, like the package list failed to merge an update once and subsequent runs cause it to fail. Or maybe there is a bug in rakudo somewhere when creating absolute paths where it loses the volume (i've encountered this bug before elsewhere).

My apologies for the problems this is causing. I use windows as my primary development OS too so this behavior is confusing.

**Comment by azawawi** [comment]
It was looking at `%USERPROFILE%\zef\.git\packages` for some reason and it was empty.

**Comment by ugexe** [comment]
It should look at the directory `my $dir = $*HOME.child(".zef").child("git").child("packages")` and see if it contains a `.git` directory. If the `.git` directory does not exist we assume we need to clone the package list to `$dir`. If `.git` does exists then do a `git pull`.

That directory shouldn't be empty though. `git` is failing to clone or pull the repo for some reason, but it *is* creating that directory (that directory is not made with perl6 mkdir but by `git` command). I think i'm using `--update-shallow` and `--depth=1` options incorrectly for git.

I made a new update that is more forceful with the `git pull` and `git clone`. Maybe this will fix it? I don't think you will have to delete `%USERPROFILE%\.zef\git\packages` first, but I could be wrong. I tested on Windows 10 installing from `%USERPROFILE%\Documents\GitHub\zef` and it clones/pulls the packages list to the separate directory `%USERPROFILE%\.zef\git\packages` (specifically p6c.json)

**Comment by ugexe** [comment]
Closing this as it pertains to an unsuported, previous version

**Comment by azawawi** [comment]
:+1:

**Pull request closed without merging**
