### PR TITLE
Enable REA, disable CPAN and p6c ecosystems by default

### PR DESCRIPTION
**Pull request by lizmat**
As per https://github.com/Raku/problem-solving/blob/master/solutions/meta/sunsetting-p6c-cpan.md

### CODE REVIEW

**Comment by lizmat** [comment]
I think you're referring to this?
````
[18:26:31]  <lizmat>	so, are you saying that anything with a ver<*> should go ?
[18:27:00]  <lizmat>	there are quite a few of the still in the live p6c ecosystem
[18:27:04]  <lizmat>	*them
[18:27:20]  <ugexe>	@dists.grep({ .ver.contains("*" || "+") || .api.contains("*" || "+") })
[18:28:55]  <ugexe>	i forget how larry described the rule when he approved of me suggesting this... like only version literals for declaring ones own ver (and hence api now)
[18:32:12]  <lizmat>	agree that :ver *should* be a version literal when in its META6
[18:32:20]  <ugexe>	:ver<*> in a META6.json would match any version request which is obviously wrong. that gets skirted in zef and CUR by treating them as version 0. but we never bothered to do anything about like 1.* or 1.0+
[18:33:01]  <lizmat>	well, if you're skirting :ver<*> now, there's about 100 modules in p6c that you cannot install with zef then
[18:33:23]  <ugexe>	well they get treated as version 0 
[18:33:50]  <ugexe>	but if they had *.* or 0+ they probably wouldnt install or would resolve strangely
[18:34:15]  <ugexe>	but i dont think anything actually does those, just the lone *
[18:35:25]  <ugexe>	that does suggest if you just filter those :ver<*> dists out and we swap REA for p6c/cpan that it wouldn't resolve the same though...
[18:36:01]  <ugexe>	so maybe you should turn those * in 0, and filter out any other version ranges as described earlier
[18:37:04]  <lizmat>	fwiw, it's my intent to fix all 110 modules that have :ver<*> before July
[18:37:39]  <lizmat>	they're a security risk, as they can get updated without it being visible
[18:38:17]  <lizmat>	$ ecosystem unversioned --verbose 
[18:38:44]  <lizmat>	either by getting the author to update them, or to fork them into raku-community-modules
````
So I'm now unsure of what you would like me to do?

- Remove all identities with `:ver<*>` in the REA?  If so, then we're going to lose 110 distributions as that's the number of distributions in the ecosystem with **just** a `:ver<*>`.

- Change them to `:ver<0>`?  If so, why, if zef already treats them as `:ver<0>` ?

- Remove all identities with `:ver<*>` from the REA that also have identities with a literal version string?  What would that bring?  Again, as zef already treats them as `:ver<0>` ?

What am I missing?

**Comment by lizmat** [comment]
Perhaps create an issue in https://github.com/raku/REA ? So that we can get clearer what the problem / possible solutions are?

**Comment by ugexe** [comment]
Whatever you used to guess versions from git history is incorrectly guessing the first version. For instance REA has a `*` version for many dists that have actual versions, and the commits picked for those are typically not the last commit before the change to a real version (which is incorrect for the first "release" of any version, although correct for any release after the first)

**Comment by ugexe** [comment]
> Ok, so this is about correcting the contents of the tar files that have a :ver<*> and have identities with literal versions. Am I understanding this correctly now?

Yes. Removing (and stop gathering) the ver/api * dists that also have a concrete version available is all that is needed, and that should avoid any potential fallout from swapping p6c/cpan with rea. Distributions that only have a * ver/api would need to remain for now with the goal of eventually removing them.

**Comment by lizmat** [comment]
https://github.com/Raku/REA/commit/1d7e9062bbfcccbd18d0615daaa3cd62a3a07dd8

**Comment by ugexe** [comment]
Thanks, I'll merge and release this weekend

**Pull request merged**
