### PR TITLE
Add zef outdated

### PR DESCRIPTION
**Pull request by rbt**
This lists modules which are outdated and the newer version. Upgrade would have performed these upgrades if executed without conditions.

### CODE REVIEW

**Comment by ugexe** [comment]
So let me prefix by saying I'm not a fan of adding new commands. If upgrade would have performed some action on those items then the upgrade command should probably be used i.e. `zef upgrade zef  --dry --/test`. We don't want to maintain 3 different slightly different sorting/selection points that all need to take the same bunch of options (which this PR doesn't include like `--/test-depends` and friends, so this PR doesn't actually show you what `zef upgrade` would install in all situations). Of course you don't get a pretty table, but zef isn't really chrome so I lean towards the deduplication of logic being worth the trade off here.

```
➜  zef git:(master) ✗ perl6 -I. bin/zef upgrade zef --/test --dry
===> Searching for: zef
The following distributions will be upgraded: zef:ver<0.8.5>:auth<github:ugexe>:api<0>
===> Updating: zef:ver<0.8.5>:auth<github:ugexe>:api<0>
```

**Comment by rbt** [comment]
What I'm looking for is a list of everything that's out of date so I can read the release notes (or commit log) to decide what, if anything, to upgrade. A summary table is also quite useful for the commit message for images.

`yarn outdated` has a very nice way of presenting it, though a change in `:api<>` covers the same information without colour coding. A nice addition would be a direct link to the source tree (since release notes on Raku modules are rare).

Perhaps a summary table after upgrade would be okay? If preferred, it could just be for --dry.

``
Old        New        Source Link
``

**Comment by ugexe** [comment]
Note you already get all the info you need:

```
===> Updating: zef:ver<0.8.5>:auth<github:ugexe>:api<0>
```

So we know the upgraded version is `0.8.5`. The version we upgrade *from* is mostly irrelevant (which is perhaps not intuitive) because we may have multiple versions installed. The only relevant bit is the name (and probably auth) due to an upgrade basically being `zef install $name` (but slightly smarter).

---

> A summary table is also quite useful for the commit messages.

zef does not have hard coupling with git. It will never have something that looks at e.g. git commit messages because nothing like those things exists for any other conceivable-but-realistic backend... CPAN files do not have commit messages, a theoretical FooCorp IPFS private repository does not have commit messages. Anyone who wants to get git commit messages can use git directly with the repository url (if one even exists). Perhaps this was what you were suggesting, but you wanted a way to see the source-url (which, again, you may incorrectly be assuming exists at all) -- you can do:

```
zef info "zef:ver<0.8.5>"

- Info for: zef:ver<0.8.5>
- Identity: zef:ver<0.8.5>:auth<github:ugexe>:api<0>
- Recommended By: Zef::Repository::Ecosystems<p6c>
- Installed: No
Description:	 A Raku / Perl 6 module manager
License:	 Artistic-2.0
Provides: 38 modules
Support:
#   bugtracker:	https://github.com/ugexe/zef/issues
#   source:	https://github.com/ugexe/zef.git
Depends: 2 items
```

or even

```
# assuming a META6 has the support.bugtracker or support.source listed:
zef browse "zef:ver<0.8.5>" bugtracker
zef browse "zef:ver<0.8.5>" source
```

**Comment by rbt** [comment]
> The version we upgrade from is mostly irrelevant (which is perhaps not intuitive) because we may have multiple versions installed.

Recording an upgrade so you can back out parts at a later time makes the previous version very relevant; both the version number and any additional information like auth.

If multiple versions are installed, it is even more important to know which old version was replaced. Chasing that down after the fact isn't nearly as easy to do.

Doing `zef list --installed, zef upgrade, zef list --installed, diff` is pretty clunky, poorly formatted, and seems error prone enough that it should be scripted.


> zef does not have hard coupling with git.

I meant showing the support.source URL if available, not pulling actual commit messages. Ideally META6 would have a support.release-notes URL which would be preferred over support.source.

My play Raku code already has 70 3rd party dependencies (direct and indirect; some I now maintain) and it isn't something I consider very complex. Doing something substantial for production would likely also require frequent maintenance.

I didn't enjoy managing a production perl environment, and it was largely the tools for dealing with CPAN that made the process clunky and time consuming.

Despite massive numbers of indirect dependencies, I don't find Node deployments onerous to maintain.

I'm trying to solve a problem before I get there. Raku code is a pleasure to write but at the moment docker image building and dev environments are kinda annoying to keep up to date.

`yarn outdated` has everything needed in a single condensed output to check to decide whether to upgrade pieces or if code adjustments might be required, can be cut & paste into a commit message cleanly, and if there are issues tells me what version to go back to on a component by component basis.
```
$ yarn outdated
yarn outdated v1.22.4
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package              Current Wanted  Latest  Package Type URL                                                  
eslint-config-google 0.9.1   0.9.1   0.14.0  dependencies https://github.com/google/eslint-config-google#readme
jsdom                16.2.2  16.3.0  16.3.0  dependencies https://github.com/jsdom/jsdom#readme                
lodash               4.17.15 4.17.19 4.17.19 dependencies https://lodash.com/                                  
sass-loader          9.0.1   9.0.2   9.0.2   dependencies https://github.com/webpack-contrib/sass-loader       
Done in 0.65s.
```

Thankfully, Raku's :api portion of the module name makes the clumsy colour coding thing unnecessary.


If you still disagree, please close this request.

**Comment by ugexe** [comment]
> which old version was replaced.

But nothing gets replaced on an upgrade, so there is no need to know what version to rollback to. Even if it did, what version would you roll back to if there were multiple versions installed before? How do you even know what versions you can replace without knowing what version every raku project depending on the global module installation (unlike javascript) path has?

> I didn't enjoy managing a production perl environment, and it was largely the tools for dealing with CPAN that made the process clunky and time consuming.

Well luckily we are so far and away from the perl module workflow that this shouldn't be a factor. I guess they both have a global module install location?

> Doing zef list --installed, zef upgrade, zef list --installed, diff is pretty clunky, poorly formatted, and seems error prone enough that it should be scripted.

Maybe. I dont think understanding how our tooling's workflow works instead of creating custom one-off commands to do $thing the same as language $x and disregard the impedance between their specs and ours. Nor does zef aim to be chrome (someone write `z` to do that). I don't think learning the tools is a big ask... the next person is just going to want it to work like `$my-favorite-package-manager`, so we can never please everyone. A simple alias even solves having to do more than a single command.

> Doing something substantial for production would likely also require frequent maintenance.

zef is actually designed primarily with production usage in mind. That why it doesn't include much superfluous chrome and instead focuses on providing the minimal core functionality needed while still being easily extensible. If you are using `zef upgrade` in production you are almost certainly trying to solve a problem in the wrong way.

> I'm trying to solve a problem before I get there.

Yes, so did I when I designed all of this years and years ago... almost nothing is ad-hoc. Features often don't need to be forced into zef as much as they often just fall out of the design. Yes, sometimes that means you have to do 2 commands instead of one... but it also means consistency is usually guaranteed.

> npm, despite being terrible in many ways, is actually pretty good for that.

npm doesn't have to solve the same problems as we do like a global install of modules of different versions. Nor is their resume-driven-development ecosystem really very similar to ours.

---

"Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away."

This is generally my philosophy. If we took away a theoretical `zef outdated` things would be fine because workflows based on primary functionality already exist and can be used to achieve the same result.

**Comment by niner** [comment]
Just a note: not every functionality has to be part of zef's core. Thanks to ugexe's desire for good architecture it's quite possible to use zef's parts in your own modules or scripts. This makes it easy to experiment with additional user interfaces and if something proves to be super useful, we can still talk about integrating it into zef itself.

**Pull request closed without merging**
