### PR TITLE
Use JSON::Fast for parsing json if installed

### PR DESCRIPTION
**Pull request by kalkin**
- On my machine this make `zef search Ddt` around ~6 seconds faster

### CODE REVIEW

**Comment by kalkin** [comment]
No Idea why AppVeyour is failing. Can you help me?

**Comment by ugexe** [comment]
Pluggable code should not be implemented in this ad-hoc way -- other runtime code allows for explicitly disabling or enabling via config and cli options, as well as being able to modify things to use *any* module ( why would JSON::Fast get to be special? ). The way this is implemented would change how zef works in the middle of zef's runtime when JSON::Fast gets installed as a dependency of something. I'm also a bit confused why the comment on *why* the comment about use of rakudo internal json parser would be removed, since its point is entirely valid.

The way to enable an alternative json parser is to extend the plugin interface to serialization.

**Comment by niner** [comment]
On Dienstag, 31. Juli 2018 00:22:58 CEST Nick Logan wrote:

> The idea isn't perfect; some might disagree with targeting the
> `Rakudo::Internals::` namespace. It also means zef and CURI can continue to
> use the same JSON parser, for better and worse.

The latter would only be true if CURI had a `use Rakudo::Internals::JSON;` 
statement.

**Comment by kalkin** [comment]
Closing because JSON::Fast is now merged in RAkudo https://github.com/rakudo/rakudo/issues/2311

**Pull request closed without merging**
